******************************************************************** 
*  ITE Tech. Inc.                               
*  PROJECT: Intel ADL_N MRD EC                  
*  UEFI Shell IT557xVG eFlash Update            
*  FILENAME: ADL_N_MRD_EC_00_29.bin  
*  BUILD DAY: 2023/01/04-16:39:16  
******************************************************************** 
mm 66 DD -w 1 -io 
mm 66 DD -w 1 -io 
ifu239 ADL_N_MRD_EC_00_29.bin 0 /mi 
