/*-----------------------------------------------------------------------------
 * TITLE: CORE_INCLUDE.H
 *
 * Author : Dino
 *
 * Note : These functions are reference only.
 *        Please follow your project software specification to do some modification.
 *---------------------------------------------------------------------------*/

#ifndef API_INCLUDE_H
#define API_INCLUDE_H 		   

#include <API_ADC.H>
#include <API_DAC.H>
#include <API_PWM.H>
#include <API_GPIO.H>
#include <API_ETWD.H>
#include <API_PECI.H>
#include <API_INTC.H>
#include <API_WUC.H>
#include <API_I2C_SLAVE.H>
#include <API_SMBUS_SLAVE.H>
#include <API_SHA1.H>
#include <API_SSPI.H>
#include <API_OW.H>

#endif